default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username:
  password:
  algorithm: scram-sha-256
  gssencmode: disable

development:
  <<: *default
  database: sparc

test:
  <<: *default
  database: sparc_test

production:
  <<: *default
  database: sparc
  username:
  password:
