default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username:
  password:

development:
  <<: *default
  database: sparc

test:
  <<: *default
  database: sparc_test

production:
  <<: *default
  database: sparc
  username:
  password:
